DROP SEQUENCE SEQ_STATE_ID;
DROP SEQUENCE SEQ_DISTRICT_ID;
DROP SEQUENCE SEQ_BLOCK_ID;
DROP SEQUENCE SEQ_VILLAGE_ID;
DROP SEQUENCE SEQ_USER_ID;
DROP sequence SEQ_ROLE_ID;

--Foreign Keys
ALTER TABLE AS_VILLAGEHEAD_MAPPING DROP CONSTRAINT FK_AS_USER_VH_ID;
ALTER TABLE AS_VILLAGEHEAD_MAPPING DROP CONSTRAINT FK_AS_VILLAGE_VH_ID;
ALTER TABLE AS_USER_ROLE_MAPPING DROP CONSTRAINT FK_AS_USER_ID; 
ALTER TABLE AS_USER_ROLE_MAPPING DROP CONSTRAINT FK_AS_ROLE_ID; 
ALTER TABLE AS_USER DROP CONSTRAINT FK_AS_VILLAGE_ID;
ALTER TABLE AS_VILLAGE DROP CONSTRAINT FK_AS_BLOCK_ID;
ALTER TABLE AS_BLOCK DROP CONSTRAINT FK_DISTRICT_ID;
ALTER TABLE AS_DISTRICT DROP CONSTRAINT FK_STATE_ID;


--Primary Keys
ALTER TABLE AS_STATE DROP CONSTRAINT PK_STATE_ID;
ALTER TABLE AS_DISTRICT DROP CONSTRAINT PK_DISTRICT_ID;
ALTER TABLE AS_BLOCK DROP CONSTRAINT PK_BLOCK_ID;
ALTER TABLE AS_VILLAGE DROP CONSTRAINT PK_AS_VILLAGE_ID;
ALTER TABLE AS_USER DROP CONSTRAINT PK_AS_USER_ID;
ALTER TABLE AS_ROLES DROP CONSTRAINT PK_AS_ROLE_ID;
ALTER TABLE AS_USER_ROLE_MAPPING DROP CONSTRAINT PK_AS_USER_ROLE_ID;
ALTER TABLE AS_VILLAGEHEAD_MAPPING DROP CONSTRAINT PK_AS_USER_VILLAGE_ID;

DROP TABLE AS_USER_ROLE_MAPPING;
DROP TABLE AS_ROLES;
DROP TABLE AS_VILLAGEHEAD_MAPPING;
DROP TABLE AS_USER;
DROP TABLE AS_VILLAGE;
DROP TABLE AS_BLOCK;
DROP TABLE AS_DISTRICT;
DROP TABLE AS_STATE;