CREATE TABLE AS_STATE(
STATE_ID NUMBER,
STATE_NAME VARCHAR2(100),
DESCRIPTION VARCHAR2(200),
STATUS VARCHAr2(1),
LAST_MODIFIED_BY VARCHAR2(200),
LAST_MODIFIED_DATE TIMESTAMP
);

CREATE TABLE AS_DISTRICT(
DISTRICT_ID NUMBER,
STATE_ID NUMBER,
DISTRICT_NAME VARCHAR2(100),
DESCRIPTION VARCHAR2(200),
STATUS VARCHAr2(1),
LAST_MODIFIED_BY VARCHAR2(200),
LAST_MODIFIED_DATE TIMESTAMP
);


CREATE TABLE AS_BLOCK(
BLOCK_ID NUMBER,
DISTRICT_ID NUMBER,
BLOCK_NAME VARCHAR2(100),
DESCRIPTION VARCHAR2(200),
STATUS VARCHAr2(1),
LAST_MODIFIED_BY VARCHAR2(200),
LAST_MODIFIED_DATE TIMESTAMP
);

CREATE TABLE AS_VILLAGE(
VILLAGE_ID NUMBER,
BLOCK_ID NUMBER,
VILLAGE_NAME VARCHAR2(200),
PINCODE NUMBER,
DESCRIPTION VARCHAR2(200),
STATUS VARCHAr2(1),
LAST_MODIFIED_BY VARCHAR2(200),
LAST_MODIFIED_DATE TIMESTAMP
);


CREATE TABLE AS_USER(
USER_ID VARCHAR2(40),
VILLAGE_ID NUMBER,
USER_NAME VARCHAR2(200),
USER_PASSWORD VARCHAR2(200),
AGE NUMBER,
DATEOFBIRTH Date,
GENDER VARCHAR2(1),
PRIMARY_CONTACT_NO varchar2(20),
SECONDARY_CONTACT_NO  varchar2(20),
EMAIL_ID VARCHAR2(200),
ACTIVE_STATUS VARCHAR2(1),
LAST_MODIFIED_BY VARCHAR2(40),
LAST_MODIFIED_DATE TIMESTAMP
);

CREATE TABLE AS_VILLAGEHEAD_MAPPING(
USER_ID VARCHAR2(40),
VILLAGE_ID NUMBER
);

CREATE TABLE AS_ROLES(
ROLE_ID NUMBER,
ROLE_NAME	VARCHAR2(20),
DESCRIPTION	VARCHAR2(50),
ACTIVE_STATUS	CHAR(1),
ROLE_TYPE	VARCHAR2(10),
LAST_MODIFIED_BY VARCHAR2(40),
LAST_MODIFIED_DATE TIMESTAMP
);

CREATE TABLE AS_USER_ROLE_MAPPING(
USER_ID VARCHAR2(40),
ROLE_ID NUMBER
);

CREATE SEQUENCE SEQ_STATE_ID MINVALUE 1 MAXVALUE 999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_DISTRICT_ID MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_BLOCK_ID MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_VILLAGE_ID MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_USER_ID MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1;
create sequence SEQ_ROLE_ID MINVALUE 1 MAXVALUE 10 INCREMENT BY 1 START WITH 1;

--Primary Keys
ALTER TABLE AS_STATE ADD CONSTRAINT PK_STATE_ID PRIMARY KEY (STATE_ID);
ALTER TABLE AS_DISTRICT ADD CONSTRAINT PK_DISTRICT_ID PRIMARY KEY (DISTRICT_ID);
ALTER TABLE AS_BLOCK ADD CONSTRAINT PK_BLOCK_ID PRIMARY KEY (BLOCK_ID);
ALTER TABLE AS_VILLAGE ADD CONSTRAINT PK_AS_VILLAGE_ID PRIMARY KEY (VILLAGE_ID);
ALTER TABLE AS_USER ADD CONSTRAINT PK_AS_USER_ID PRIMARY KEY (USER_ID);
ALTER TABLE AS_ROLES ADD CONSTRAINT PK_AS_ROLE_ID PRIMARY KEY (ROLE_ID);
ALTER TABLE AS_USER_ROLE_MAPPING ADD CONSTRAINT PK_AS_USER_ROLE_ID PRIMARY KEY (USER_ID,ROLE_ID);
ALTER TABLE AS_VILLAGEHEAD_MAPPING ADD CONSTRAINT PK_AS_USER_VILLAGE_ID PRIMARY KEY (USER_ID,VILLAGE_ID);

--Foreign Keys
ALTER TABLE AS_DISTRICT ADD CONSTRAINT FK_STATE_ID FOREIGN KEY (STATE_ID) REFERENCES AS_STATE (STATE_ID);
ALTER TABLE AS_BLOCK ADD CONSTRAINT FK_DISTRICT_ID FOREIGN KEY (DISTRICT_ID) REFERENCES AS_DISTRICT (DISTRICT_ID);
ALTER TABLE AS_VILLAGE ADD CONSTRAINT FK_AS_BLOCK_ID FOREIGN KEY (BLOCK_ID) REFERENCES AS_BLOCK (BLOCK_ID);
ALTER TABLE AS_USER ADD CONSTRAINT FK_AS_VILLAGE_ID FOREIGN KEY (VILLAGE_ID) REFERENCES AS_VILLAGE (VILLAGE_ID);
ALTER TABLE AS_USER_ROLE_MAPPING ADD CONSTRAINT FK_AS_USER_ID FOREIGN KEY (USER_ID) REFERENCES AS_USER (USER_ID);
ALTER TABLE AS_USER_ROLE_MAPPING ADD CONSTRAINT FK_AS_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AS_ROLES (ROLE_ID);
ALTER TABLE AS_VILLAGEHEAD_MAPPING ADD CONSTRAINT FK_AS_USER_VH_ID FOREIGN KEY (USER_ID) REFERENCES AS_USER (USER_ID);
ALTER TABLE AS_VILLAGEHEAD_MAPPING ADD CONSTRAINT FK_AS_VILLAGE_VH_ID FOREIGN KEY (VILLAGE_ID) REFERENCES AS_VILLAGE (VILLAGE_ID);
